import json
import io
import matplotlib.patches as patches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from iapws import IAPWS97
from matplotlib.backends.backend_pdf import PdfPages
from streamlit_javascript import st_javascript

from core.thermo import get_iapws_robust, steam_point_to_dict, GasPoint, get_polytropic_path
from core.cycles import calc_otto, calc_diesel, calc_brayton, calc_frigorifico, calc_carnot
from components.ui import apply_custom_style, plotly_base, render_hero, render_metric_row, add_line, add_generic_points, add_steam_dome, add_steam_points
from config.theme import THEME

st.set_page_config(page_title="TermoWeb UI", page_icon="⚡", layout="wide")
apply_custom_style()


def get_browser_lang():
    try:
        js_code = "navigator.language || navigator.userLanguage || 'it'"
        lang = st_javascript(js_code)
        if lang and isinstance(lang, str):
            return "en" if lang.startswith("en") else "it"
    except Exception:
        pass
    return "it"


def load_translations(lang):
    try:
        with open(f"translations/{lang}.json", "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


if "app_lang" not in st.session_state:
    st.session_state["app_lang"] = "it"

dict_t = load_translations("en")
dict_t.update(load_translations("it"))


with st.sidebar:
    st.title("🌐 Language")
    lang_choice = st.radio("", ["Italiano", "English"],
                           index=0 if st.session_state["app_lang"] == "it" else 1,
                           horizontal=True)
    lang = "it" if "Italiano" in lang_choice else "en"
    st.session_state["app_lang"] = lang
    t = dict_t.get(lang, {})

render_hero(t)
st.divider()


def quality_label(x):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "n/d"
    if 0.0 < x < 1.0:
        return f"{x:.3f}"
    if x <= 0.0:
        return "liq. sat."
    if x >= 1.0:
        return "vap. sat."
    return f"{x:.3f}"


def steam_point(name, state):
    return {"name": name, "P": state.P * 10.0, "T": state.T - 273.15, "h": state.h, "s": state.s, "v": state.v, "x": state.x}


def create_pdf_report(cycle_name, report_text, points_df, fig_ts=None):
    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        fig_rep = plt.figure(figsize=(8.27, 11.69))
        plt.axis('off')
        plt.text(0.1, 0.95, f"THERMODYNAMIC ANALYSIS: {cycle_name.upper()}", fontsize=14, fontweight='bold', family='monospace')
        plt.text(0.1, 0.1, report_text, fontsize=9, family='monospace', verticalalignment='top')
        plt.text(0.1, 0.05, "Generated by Thermodynamic CAD Web", fontsize=8, fontstyle='italic')
        pdf.savefig(fig_rep)
        plt.close(fig_rep)

        if not points_df.empty:
            fig_tab, ax_tab = plt.subplots(figsize=(8.27, 4))
            ax_tab.axis('off')
            the_table = ax_tab.table(cellText=points_df.values, colLabels=points_df.columns, loc='center', cellLoc='center')
            the_table.auto_set_font_size(False)
            the_table.set_fontsize(8)
            the_table.scale(1.2, 1.2)
            plt.title("State Point Table", fontsize=12, fontweight='bold')
            pdf.savefig(fig_tab)
            plt.close(fig_tab)
    buf.seek(0)
    return buf


def download_report_btn(name, report, df, key):
    pdf_buf = create_pdf_report(name, report, df, None)
    st.download_button(label=f"📥 Scarica Report PDF ({name})",
                       data=pdf_buf,
                       file_name=f"Report_{name.replace(' ', '_')}.pdf",
                       mime="application/pdf",
                       key=key)


def download_csv_btn(df, name, key):
    csv = df.to_csv(index=False).encode('utf-8')
    st.download_button(label=f"📊 Esporta CSV ({name})", data=csv, file_name=f"{name}.csv", mime="text/csv", key=key)


def export_plotly_png(fig, name, key):
    try:
        fig.write_image(f"{name}.png")
        with open(f"{name}.png", "rb") as f:
            st.download_button(label=f"🖼️ Esporta PNG ({name})", data=f, file_name=f"{name}.png", mime="image/png", key=key)
    except Exception as e:
        st.warning(f"Export PNG non disponibile: {e}")


def draw_rankine_schema(p1, p2, p3, p4):
    fig_s, ax = plt.subplots(figsize=(6, 5))
    ax.set_facecolor("#ffffff")
    ax.axis("off")
    ax.set_xlim(0, 10.5)
    ax.set_ylim(-2, 11)
    ax.add_patch(patches.Rectangle((1.5, 3.5), 2.5, 4.5, fill=True, color="#2c1e1e", ec=THEME["red"], lw=2))
    ax.add_patch(patches.Polygon([(6.5, 7.5), (7.8, 6.8), (7.8, 4.2), (6.5, 3.5)], fill=True, color="#2f2214", ec=THEME["orange"], lw=2))
    ax.add_patch(patches.Circle((7.15, 1.5), 0.8, fill=True, color="#1a2433", ec=THEME["blue"], lw=2))
    ax.add_patch(patches.Circle((4, 0.5), 0.5, fill=True, color="#1a3333", ec=THEME["cyan"], lw=2))
    ax.text(2.75, 5.75, "Caldaia", color=THEME["red"], ha="center", va="center", weight="bold")
    ax.text(7.15, 8.2, "Turbina", color=THEME["orange"], ha="center", weight="bold")
    ax.text(8.8, 1.5, "Condensatore", color=THEME["blue"], ha="center", va="center", weight="bold")
    ax.text(4, 1.5, "Pompa", color=THEME["cyan"], ha="center", weight="bold")
    ax.plot([3.5, 2.75, 2.75], [0.5, 0.5, 3.5], color=THEME["cyan"], lw=2)
    ax.plot([2.75, 2.75, 6.5, 6.5], [8.0, 9.5, 9.5, 7.5], color=THEME["red"], lw=2)
    ax.plot([7.15, 7.15], [5.5, 2.3], color=THEME["orange"], lw=2)
    ax.plot([6.35, 4.5, 4.5, 4.0], [1.5, 1.5, 0.5, 0.5], color=THEME["blue"], lw=2)
    for x, y, lbl, p in [(4.5, 0.5, "1", p1), (2.75, 2.0, "2", p2), (4.5, 9.7, "3", p3), (7.3, 3.5, "4", p4)]:
        ax.text(x, y, f"[{lbl}]\nP:{p.P*10:.2f} bar\nT:{p.T-273.15:.1f} °C", color=THEME["text"], fontsize=7, bbox=dict(boxstyle="round,pad=0.2", fc="#ffffff", ec=THEME["text"], alpha=0.9))
    return fig_s


def draw_brayton_schema(p1, p2, p3, p4):
    fig_s, ax = plt.subplots(figsize=(6, 5))
    ax.set_facecolor("#ffffff")
    ax.axis("off")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.plot([0.3, 0.9], [0.4, 0.4], color="#333333", linewidth=4, zorder=1)
    ax.text(0.6, 0.35, "Albero", color=THEME["text"], weight="bold", ha="center", fontsize=9)
    ax.add_patch(patches.Polygon([[0.2, 0.3], [0.2, 0.7], [0.4, 0.6], [0.4, 0.4]], closed=True, color="#2196F3", zorder=2))
    ax.add_patch(patches.Polygon([[0.6, 0.4], [0.6, 0.6], [0.8, 0.7], [0.8, 0.3]], closed=True, color="#4CAF50", zorder=2))
    ax.add_patch(patches.Rectangle((0.4, 0.7), 0.2, 0.2, color="#FFCA28", zorder=2))
    ax.text(0.3, 0.5, "Compressore", color="#222222", weight="bold", ha="center", va="center", rotation=90, fontsize=8)
    ax.text(0.7, 0.5, "Turbina", color="#222222", weight="bold", ha="center", va="center", rotation=-90, fontsize=8)
    ax.text(0.5, 0.8, "Combustore", color="black", weight="bold", ha="center", va="center", fontsize=8)
    for x, y, lbl, p in [(0.1, 0.5, "1", p1), (0.35, 0.9, "2", p2), (0.65, 0.9, "3", p3), (0.9, 0.5, "4", p4)]:
        ax.text(x, y, f"{lbl}\nP:{p['P']:.1f} bar\nT:{p['T']:.0f} °C", color=THEME["text"], fontsize=7, bbox=dict(boxstyle="round,pad=0.2", fc="#ffffff", ec=THEME["text"], alpha=0.9))
    return fig_s


def draw_otto_diesel_schema(is_diesel=False):
    fig_s, ax = plt.subplots(figsize=(6, 4))
    ax.add_patch(patches.Rectangle((0.3, 0.2), 0.4, 0.6, fill=False, color=THEME["text"], lw=3))
    piston_y = 0.3 if is_diesel else 0.4
    ax.add_patch(patches.Rectangle((0.3, piston_y), 0.4, 0.1, color="gray"))
    ax.plot([0.5, 0.5], [piston_y, 0.05], color="gray", lw=5)
    ax.text(0.5, 0.9, "Diesel" if is_diesel else "Otto", color=THEME["text"], ha="center", weight="bold")
    return fig_s


def render_point_table(points):
    df = pd.DataFrame(points)
    cols = [c for c in ["name", "P", "T", "h", "s", "v", "x"] if c in df.columns]
    st.dataframe(df[cols], use_container_width=True, hide_index=True)


cycle_options = [
    "💧 Acqua & Vapore (CAD)",
    "🔥 Brayton (CAD)",
    "⚙️ Ciclo Otto",
    "🛢️ Ciclo Diesel",
    "❄️ Frigorifero",
    "🔄 Ciclo Carnot",
    "🎨 Laboratorio Aria (CAD)"
]

st.sidebar.header(t.get("sidebar_head", "Cicli e Impostazioni"))
ciclo = st.sidebar.radio(t.get("select_cycle", "Seleziona ciclo"), cycle_options)

for key, default in [("water_pts", []), ("water_components", []), ("water_portata", 100.0),
                      ("cad_points", []), ("cad_close_cycle", True)]:
    if key not in st.session_state:
        st.session_state[key] = default


def add_water_pt(name, **args):
    state = get_iapws_robust(**args)
    if state:
        st.session_state["water_pts"].append(steam_point(name, state))
        return True
    return False


if "Acqua" in ciclo:
    st.header("💧 Water Cycle & Rankine CAD")
    col_in, col_main = st.columns([1, 2.5], gap="large")

    with col_in:
        st.subheader("1. ➕ Add State Point")
        p_mode = st.selectbox("Property Mask", ["P-T", "P-x", "P-s", "P-h", "T-x"], key="w_p_mode")
        v1 = st.number_input("Value 1", value=50.0, format="%.3f", key="w_v1")
        v2 = st.number_input("Value 2", value=450.0, format="%.3f", key="w_v2")
        p_name = st.text_input("Point Name", value=f"P{len(st.session_state['water_pts'])+1}", key="w_name")

        if st.button("Add Point", use_container_width=True):
            args = {}
            if p_mode == "P-T":
                args = {"P": v1 / 10.0, "T": v2 + 273.15}
            elif p_mode == "P-x":
                args = {"P": v1 / 10.0, "x": v2}
            elif p_mode == "P-s":
                args = {"P": v1 / 10.0, "s": v2}
            elif p_mode == "P-h":
                args = {"P": v1 / 10.0, "h": v2}
            elif p_mode == "T-x":
                args = {"T": v1 + 273.15, "x": v2}
            if add_water_pt(p_name, **args):
                st.rerun()
            else:
                st.error("Invalid thermodynamic state.")

        st.divider()
        st.subheader("2. ⚙️ Define Component")
        if len(st.session_state["water_pts"]) >= 2:
            p_names = [p["name"] for p in st.session_state["water_pts"]]
            c_type = st.selectbox("Type", ["Turbina", "Pompa", "Caldaia/Risur.", "Condensatore", "Mixer/FWH"], key="w_c_type")
            c_in = st.selectbox("Inlet", p_names, key="w_c_in")
            c_out = st.selectbox("Outlet", p_names, key="w_c_out")
            c_y = st.number_input("Mass Fraction (y)", value=1.0, step=0.01, key="w_c_y")
            if st.button("Add Component", use_container_width=True):
                st.session_state["water_components"].append({"type": c_type, "in": c_in, "out": c_out, "y": c_y})
                st.rerun()
        else:
            st.info("Add at least 2 points to define components.")

        st.divider()
        st.subheader(t.get("global_params", "Parametri Globali"))
        st.session_state["water_portata"] = st.number_input(t.get("flow", "Portata") + " (kg/s)", value=st.session_state["water_portata"])
        if st.button(t.get("reset", "Resetta"), type="primary", use_container_width=True):
            st.session_state["water_pts"] = []
            st.session_state["water_components"] = []
            st.rerun()

    w_pts = st.session_state["water_pts"]
    w_comp = st.session_state["water_components"]
    l_t = l_p = q_in = q_out = 0.0

    def get_pt(name):
        return next((p for p in w_pts if p["name"] == name), None)

    comp_details = []
    for c in w_comp:
        pt1, pt2 = get_pt(c["in"]), get_pt(c["out"])
        if not pt1 or not pt2:
            continue
        dh = pt2["h"] - pt1["h"]
        y = c["y"]
        if c["type"] == "Turbina":
            l_t += abs(dh) * y
        elif c["type"] == "Pompa":
            l_p += abs(dh) * y
        elif c["type"] == "Caldaia/Risur.":
            q_in += dh * y
        elif c["type"] == "Condensatore":
            q_out += abs(dh) * y
        comp_details.append(f"  {c['type']:<15} : {c['in']} ➜ {c['out']} | y={y:.3f} | Δh={dh:>8.2f} kJ/kg")

    l_net = l_t - l_p
    eta_cycle = (l_net / q_in) * 100 if q_in > 0 else 0
    p_net = l_net * st.session_state["water_portata"]

    with col_main:
        render_metric_row({
            t.get("net_work", "Lavoro Netto"): f"{l_net:.2f} kJ/kg",
            t.get("efficiency", "Rendimento"): f"{eta_cycle:.2f} %",
            t.get("net_power", "Potenza Netta"): f"{p_net / 1000:.2f} MW"
        })

        tab_list, tab_ts, tab_pv, tab_hs, tab_rep = st.tabs([t.get("points", "Punti"), "T-s Diagram", "P-v Diagram", "h-s Diagram", t.get("results", "Risultati")])

        with tab_list:
            render_point_table(w_pts)
            st.subheader(t.get("components", "Componenti"))
            for i, c in enumerate(w_comp):
                c_col1, c_col2 = st.columns([4, 1])
                c_col1.write(f"**{c['type']}**: {c['in']} ➜ {c['out']} (y={c['y']})")
                if c_col2.button("🗑️", key=f"del_c_{i}"):
                    st.session_state["water_components"].pop(i)
                    st.rerun()

        with tab_ts:
            fig = plotly_base("Diagramma T-s (Acqua/Vapore)", "s (kJ/kgK)", "T (°C)", THEME)
            add_steam_dome(fig, "s", "T")
            if w_pts:
                add_steam_points(fig, w_pts, "s", "T", "Punti di Stato", THEME["gold"])
            if len(w_pts) > 2 and st.session_state["cad_close_cycle"]:
                path_pts = w_pts + [w_pts[0]]
                add_line(fig, [p["s"] for p in path_pts], [p["T"] for p in path_pts], "Percorso", THEME["cyan"], dash="dot", width=1)
            st.plotly_chart(fig, use_container_width=True)

        with tab_pv:
            fig = plotly_base("Diagramma P-v", "v (m³/kg)", "P (bar)", THEME, xlog=True, ylog=True)
            add_steam_dome(fig, "v", "P")
            if w_pts:
                add_steam_points(fig, w_pts, "v", "P", "Punti di Stato", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_hs:
            fig = plotly_base("Diagramma Mollier h-s", "s (kJ/kgK)", "h (kJ/kg)", THEME)
            add_steam_dome(fig, "s", "h")
            if w_pts:
                add_steam_points(fig, w_pts, "s", "h", "Punti di Stato", THEME["red"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_rep:
            comp_txt = "\n".join(comp_details) if comp_details else "  (Nessun componente definito)"
            rep = f"""
═════════════════════════════════════════════════════════════
             REPORT ANALISI CICLO H2O (CAD)
═════════════════════════════════════════════════════════════

-- ANALISI COMPONENTI --------------------------------------
{comp_txt}

-- BILANCIO ENERGETICO -------------------------------------
   Lavoro Turbina:   {l_t:>8.2f} kJ/kg
   Lavoro Pompa:     {l_p:>8.2f} kJ/kg
   Calore Intro:     {q_in:>8.2f} kJ/kg
   Calore Ceduto:    {q_out:>8.2f} kJ/kg

-- PRESTAZIONI GLOBALI -------------------------------------
   LAVORO NETTO:     {l_net:>8.2f} kJ/kg
   POTENZA NETTA:    {p_net / 1000:>8.3f} MW
   REND. CICLO:      {eta_cycle:>8.2f} %
   Portata ṁ:        {st.session_state['water_portata']:>8.2f} kg/s
═════════════════════════════════════════════════════════════
            """
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Acqua", rep, pd.DataFrame(w_pts), "pdf_w")


elif "Brayton" in ciclo:
    st.header("🔥 Brayton – Gas Turbine CAD")
    col_in, col_main = st.columns([1, 2.5], gap="large")

    with col_in:
        st.subheader(t.get("inputs", "Parametri"))
        with st.expander("A. Compression & Ambient", expanded=True):
            p1 = st.number_input("P1 (bar)", value=1.013, format="%.3f")
            t1 = st.number_input("T1 (°C)", value=15.0)
            p2 = st.number_input("P2 (bar)", value=12.0)
            cpa = st.number_input("cp_air (kJ/kgK)", value=1.005, format="%.3f")
            ka = st.number_input("k_air", value=1.40, format="%.2f")
            eta_ic = st.number_input("η_is Compressor", value=0.85, step=0.01)

        with st.expander("B. Combustion & Fuel", expanded=True):
            t3 = st.number_input("T3 Max (°C)", value=1100.0)
            hi = st.number_input("Hi Fuel (kJ/kg)", value=42000.0, step=100.0)
            eta_cc = st.number_input("η_combustor", value=0.98, step=0.01)
            cpg_comb = st.number_input("cp_gas (comb)", value=1.15, format="%.3f")
            a0 = st.number_input("Stoich. Air (a0)", value=14.7, format="%.1f")

        with st.expander("C. Expansion & Mechanical", expanded=True):
            p4 = st.number_input("P4 Exit (bar)", value=1.013, format="%.3f")
            eta_it = st.number_input("η_is Turbine", value=0.88, step=0.01)
            cpg_esp = st.number_input("cp_gas (exp)", value=1.10, format="%.3f")
            kg = st.number_input("k_gas", value=1.33, format="%.2f")
            eta_m = st.number_input("η_mechanical", value=0.99, step=0.01)
            m_dot = st.number_input("Air Flow ṁ (kg/s)", value=50.0)

    pts_real, pts_ideal, results = calc_brayton(p1, t1, p2, t3, cpa, ka, eta_ic, eta_it)

    p_e_netta = results["w_net"] * m_dot
    eta_te = results["eta"]
    bwr = results["bwr"]

    with col_main:
        render_metric_row({
            t.get("net_work", "Lavoro Netto"): f"{p_e_netta / 1000:.2f} MW",
            t.get("efficiency", "Rendimento"): f"{eta_te:.2f} %",
            t.get("bwr", "BWR"): f"{bwr:.1f} %"
        })

        tab_flow, tab_ts, tab_pv, tab_rep = st.tabs([t.get("schema", "Schema"), "T-s Diagram", "P-v Diagram", t.get("results", "Risultati")])

        with tab_flow:
            st.pyplot(draw_brayton_schema(pts_real[0].to_dict(), pts_real[1].to_dict(), pts_real[2].to_dict(), pts_real[3].to_dict()))

        with tab_ts:
            fig = plotly_base("Diagramma T-s (Gas Reale)", "s (kJ/kgK)", "T (°C)", THEME)
            for pa, pb in zip(pts_real[:-1], pts_real[1:]):
                path = get_polytropic_path(pa, pb)
                add_line(fig, [p["s"] for p in path], [p["T"] for p in path], "Reale", THEME["orange"], width=3)
            for pa, pb in zip(pts_ideal[:-1], pts_ideal[1:]):
                path = get_polytropic_path(pa, pb)
                add_line(fig, [p["s"] for p in path], [p["T"] for p in path], "Ideale", THEME["gray"], dash="dash", width=1)
            add_generic_points(fig, [p.to_dict() for p in pts_real[:-1]], "s", "T", "Punti", THEME["gold"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_pv:
            fig = plotly_base("Diagramma P-v (Gas Reale)", "v (m³/kg)", "P (bar)", THEME, xlog=True)
            for pa, pb in zip(pts_real[:-1], pts_real[1:]):
                path = get_polytropic_path(pa, pb)
                add_line(fig, [p["v"] for p in path], [p["P"] for p in path], "Reale", THEME["cyan"], width=3)
            add_generic_points(fig, [p.to_dict() for p in pts_real[:-1]], "v", "P", "Punti", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_rep:
            rep = f"""
═════════════════════════════════════════════════════════════
             REPORT ANALISI CICLO BRAYTON
═════════════════════════════════════════════════════════════

-- PRESTAZIONI ---------------------------------------------
   POT. NETTA:   {p_e_netta / 1000:>8.3f} MW
   REND. EFF.:   {eta_te:>8.2f} %
   BWR:          {bwr:>8.2f} %
═════════════════════════════════════════════════════════════
            """
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Brayton", rep, pd.DataFrame([p.to_dict() for p in pts_real[:-1]]), "pdf_b")


elif "Otto" in ciclo:
    st.header("⚙️ Otto Cycle Engine CAD")
    col_in, col_main = st.columns([1, 2.5], gap="large")

    with col_in:
        st.subheader(t.get("inputs", "Parametri"))
        p1 = st.number_input("P1 Intake (bar)", value=1.0)
        t1 = st.number_input("T1 Intake (°C)", value=25.0)
        r = st.number_input("Compression Ratio r", value=9.0)
        t3 = st.number_input("T3 Peak (°C)", value=1200.0)
        k = st.number_input("k (exp.)", value=1.4)
        cv = st.number_input("cv (kJ/kgK)", value=0.718)
        eta = st.number_input("η isentropic", value=0.85)

        with st.expander(t.get("parametric", "Analisi Parametrica")):
            enable_sweep = st.checkbox("Abilita sweep parametro")
            sweep_param = "r"
            r_min, r_max = st.slider("Range r", 6.0, 20.0, (6.0, 20.0))
            if enable_sweep:
                r_vals = np.linspace(r_min, r_max, 20)
                eta_vals = []
                for rv in r_vals:
                    _, res = calc_otto(p1, t1, rv, t3, k, cv, eta)
                    eta_vals.append(res["eta"])
                fig_sweep = go.Figure()
                fig_sweep.add_trace(go.Scatter(x=r_vals, y=eta_vals, mode='lines+markers', name='η'))
                fig_sweep.update_layout(xaxis_title="r", yaxis_title="η (%)", title="Rendimento vs Rapporto Compressione")
                st.plotly_chart(fig_sweep, use_container_width=True)

    pts, results = calc_otto(p1, t1, r, t3, k, cv, eta)
    w_net = results["w_net"]
    eta_cycle = results["eta"]
    p3 = results["P_max"]

    with col_main:
        render_metric_row({
            t.get("net_work", "Lavoro Netto"): f"{w_net:.1f} kJ/kg",
            t.get("efficiency", "Rendimento"): f"{eta_cycle:.2f} %",
            t.get("pmax", "Pmax"): f"{p3:.2f} bar"
        })

        tab_flow, tab_pv, tab_ts, tab_rep = st.tabs([t.get("schema", "Schema"), "P-v Diagram", "T-s Diagram", t.get("results", "Risultati")])
        with tab_flow:
            st.pyplot(draw_otto_diesel_schema(False))
        with tab_pv:
            fig = plotly_base("Diagramma P-v (Otto)", "v (m³/kg)", "P (bar)", THEME)
            for pa, pb in zip(pts[:-1], pts[1:]):
                path = get_polytropic_path(pa, pb)
                add_line(fig, [p["v"] for p in path], [p["P"] for p in path], "Ciclo", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)
        with tab_ts:
            fig = plotly_base("Diagramma T-s (Otto)", "s (kJ/kgK)", "T (°C)", THEME)
            for pa, pb in zip(pts[:-1], pts[1:]):
                path = get_polytropic_path(pa, pb)
                add_line(fig, [p["s"] for p in path], [p["T"] for p in path], "Ciclo", THEME["gold"])
            st.plotly_chart(fig, use_container_width=True)
        with tab_rep:
            rep = f"PEAK PRESSURE: {p3:>8.2f} bar\nNET WORK:      {w_net:>8.2f} kJ/kg\nEFFICIENCY:    {eta_cycle:>8.2f} %"
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Otto", rep, pd.DataFrame([p.to_dict() for p in pts[:-1]]), "pdf_o")
            download_csv_btn(pd.DataFrame([p.to_dict() for p in pts[:-1]]), "Otto", "csv_o")


elif "Diesel" in ciclo:
    st.header("🛢️ Diesel Cycle Engine CAD")
    col_in, col_main = st.columns([1, 2.5], gap="large")

    with col_in:
        st.subheader(t.get("inputs", "Parametri"))
        p1 = st.number_input("P1 Intake (bar)", value=1.0)
        t1 = st.number_input("T1 Intake (°C)", value=25.0)
        r = st.number_input("Compression Ratio r", value=18.0)
        rc = st.number_input("Cut-off Ratio rc", value=2.0)
        k = st.number_input("k (exp.)", value=1.4)
        cv = st.number_input("cv (kJ/kgK)", value=0.718)
        eta = st.number_input("η isentropic", value=0.85)

    pts, results = calc_diesel(p1, t1, r, rc, k, cv, eta)
    w_net = results["w_net"]
    eta_cycle = results["eta"]
    p3 = results["P_max"]

    with col_main:
        render_metric_row({
            t.get("net_work", "Lavoro Netto"): f"{w_net:.1f} kJ/kg",
            t.get("efficiency", "Rendimento"): f"{eta_cycle:.2f} %",
            t.get("pmax", "Pmax"): f"{p3:.2f} bar"
        })

        tab_flow, tab_pv, tab_ts, tab_rep = st.tabs([t.get("schema", "Schema"), "P-v Diagram", "T-s Diagram", t.get("results", "Risultati")])
        with tab_flow:
            st.pyplot(draw_otto_diesel_schema(True))
        with tab_pv:
            fig = plotly_base("Diagramma P-v (Diesel)", "v (m³/kg)", "P (bar)", THEME)
            for pa, pb in zip(pts[:-1], pts[1:]):
                path = get_polytropic_path(pa, pb)
                add_line(fig, [p["v"] for p in path], [p["P"] for p in path], "Ciclo", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)
        with tab_ts:
            fig = plotly_base("Diagramma T-s (Diesel)", "s (kJ/kgK)", "T (°C)", THEME)
            for pa, pb in zip(pts[:-1], pts[1:]):
                path = get_polytropic_path(pa, pb)
                add_line(fig, [p["s"] for p in path], [p["T"] for p in path], "Ciclo", THEME["gold"])
            st.plotly_chart(fig, use_container_width=True)
        with tab_rep:
            rep = f"PEAK PRESSURE: {p3:>8.2f} bar\nNET WORK:      {w_net:>8.2f} kJ/kg\nEFFICIENCY:    {eta_cycle:>8.2f} %"
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Diesel", rep, pd.DataFrame([p.to_dict() for p in pts[:-1]]), "pdf_d")


elif "Frigorifero" in ciclo:
    st.header("❄️ Refrigeration Cycle CAD (R134a)")
    col_in, col_main = st.columns([1, 2.5], gap="large")

    with col_in:
        st.subheader(t.get("inputs", "Parametri"))
        te = st.number_input("T Evaporation (°C)", value=-15.0)
        tc = st.number_input("T Condensation (°C)", value=40.0)
        eta_c = st.number_input("η compressor", value=0.82)
        m_dot = st.number_input("Mass flow (kg/s)", value=0.5)
        superheat = st.number_input("Surriscaldamento (K)", value=0.0)
        subcooling = st.number_input("Sottoraffreddamento (K)", value=0.0)

    pts, results = calc_frigorifico(te, tc, eta_c, superheat, subcooling, m_dot)
    cop = results["COP_f"]
    qe_kw = results["Q_evap_kW"]
    wc_kw = results["W_c_kW"]

    with col_main:
        render_metric_row({
            "COP": f"{cop:.2f}",
            t.get("heat_in", "Q_evap"): f"{qe_kw:.1f} kW",
            "WC": f"{wc_kw:.1f} kW"
        })

        tab_ph, tab_ts, tab_rep = st.tabs(["P-h Diagram", "T-s Diagram", t.get("results", "Risultati")])

        dome = results.get("dome", {})
        with tab_ph:
            fig = plotly_base("Diagramma P-h (R134a)", "h (kJ/kg)", "P (bar)", THEME, ylog=True)
            if dome:
                fig.add_trace(go.Scatter(x=dome["hf"] + dome["hg"][::-1], y=dome["Pf"] + dome["Pf"][::-1],
                                         mode='lines', name='Saturation', line=dict(color='gray', dash='dash')))
            add_generic_points(fig, pts, "h", "P", "Ciclo Frigo", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_ts:
            fig = plotly_base("Diagramma T-s (R134a)", "s (kJ/kgK)", "T (°C)", THEME)
            if dome:
                fig.add_trace(go.Scatter(x=dome["sf"] + dome["sg"][::-1], y=dome["T"] + dome["T"][::-1],
                                         mode='lines', name='Saturation', line=dict(color='gray', dash='dash')))
            add_generic_points(fig, pts, "s", "T", "Ciclo Frigo", THEME["gold"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_rep:
            rep = f"COP REFRIG:  {cop:>8.2f}\nQ_EVAP:       {qe_kw:>8.2f} kW\nW_COMP:       {wc_kw:>8.2f} kW"
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Frigorifero", rep, pd.DataFrame(pts[:-1]), "pdf_f")


elif "Carnot" in ciclo:
    st.header("🔄 Carnot Cycle (Ideal)")
    col_in, col_main = st.columns([1, 2.5], gap="large")

    with col_in:
        st.subheader(t.get("inputs", "Parametri"))
        th_c = st.number_input("T High (°C)", value=400.0)
        tl_c = st.number_input("T Low (°C)", value=30.0)
        p_ref = st.number_input("P Reference (bar)", value=1.0)
        ds = st.number_input("Δs (kJ/kgK)", value=0.5)

    pts, results = calc_carnot(th_c, tl_c, p_ref, ds)
    eta_carnot = results["eta"]
    w_net = results["w_net"]

    with col_main:
        render_metric_row({
            t.get("efficiency", "η Carnot"): f"{eta_carnot:.2f} %",
            t.get("net_work", "W_net"): f"{w_net:.1f} kJ/kg"
        })

        tab_ts, tab_pv, tab_rep = st.tabs(["T-s Diagram", "P-v Diagram", t.get("results", "Risultati")])

        with tab_ts:
            fig = plotly_base("Diagramma T-s (Carnot)", "s (kJ/kgK)", "T (°C)", THEME)
            for pa, pb in zip(pts[:-1], pts[1:]):
                path = get_polytropic_path(pa, pb)
                add_line(fig, [p["s"] for p in path], [p["T"] for p in path], "Ciclo", THEME["green"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_pv:
            fig = plotly_base("Diagramma P-v (Carnot)", "v (m³/kg)", "P (bar)", THEME, xlog=True)
            for pa, pb in zip(pts[:-1], pts[1:]):
                path = get_polytropic_path(pa, pb)
                add_line(fig, [p["v"] for p in path], [p["P"] for p in path], "Ciclo", THEME["blue"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_rep:
            rep = f"η CARNOT:   {eta_carnot:>8.2f} %\nW_NET:       {w_net:>8.2f} kJ/kg\nT_HIGH:      {th_c:>8.1f} °C\nT_LOW:       {tl_c:>8.1f} °C"
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Carnot", rep, pd.DataFrame([p.to_dict() for p in pts[:-1]]), "pdf_c")


else:
    st.header("🎨 Laboratorio Aria (CAD)")
    st.info(t.get("build_info", "Costruzione libera di cicli complessi con supporto multi-fase."))

    with st.sidebar:
        st.divider()
        st.subheader(t.get("add_point", "Aggiungi Punto"))
        point_mode = st.selectbox("Metodo / Method", ["P-T", "P-x", "P-s", "P-h", "T-x", "T-s"])
        val1 = st.number_input("Valore / Value 1", value=1.0, format="%.4f", key="cad_v1")
        val2 = st.number_input("Valore / Value 2", value=20.0, format="%.4f", key="cad_v2")
        if st.button("Aggiungi punto / Add point", use_container_width=True):
            args = {}
            if point_mode == "P-T":
                args = {"P": val1 / 10.0, "T": val2 + 273.15}
            elif point_mode == "P-x":
                args = {"P": val1 / 10.0, "x": val2}
            elif point_mode == "P-s":
                args = {"P": val1 / 10.0, "s": val2}
            elif point_mode == "P-h":
                args = {"P": val1 / 10.0, "h": val2}
            elif point_mode == "T-x":
                args = {"T": val1 + 273.15, "x": val2}
            elif point_mode == "T-s":
                args = {"T": val1 + 273.15, "s": val2}
            state = get_iapws_robust(**args)
            if state:
                st.session_state["cad_points"].append(steam_point(f"P{len(st.session_state['cad_points']) + 1}", state))
                st.rerun()
            else:
                st.error("Stato non valido / Invalid state")

        st.checkbox("Chiudi il ciclo / Close cycle", key="cad_close_cycle")
        if st.button("Rimuovi ultimo punto / Remove last point", use_container_width=True):
            if st.session_state["cad_points"]:
                st.session_state["cad_points"].pop()
                st.rerun()
        if st.button(t.get("reset", "Resetta"), type="primary", use_container_width=True):
            st.session_state["cad_points"] = []
            st.rerun()

    if st.session_state["cad_points"]:
        points = list(st.session_state["cad_points"])
        closed_points = points + [points[0]] if st.session_state["cad_close_cycle"] and len(points) > 2 else points

        col_list, col_plot = st.columns([1, 1.8])
        with col_list:
            st.subheader(t.get("points", "Punti"))
            render_point_table(points)
            st.subheader(t.get("stats", "Statistiche"))
            if len(closed_points) > 1:
                q_in = q_out = l_net = 0.0
                for p_a, p_b in zip(closed_points[:-1], closed_points[1:]):
                    dh = p_b["h"] - p_a["h"]
                    l_net -= dh
                    if dh >= 0:
                        q_in += dh
                    else:
                        q_out += abs(dh)
                eta_cycle = 100.0 * l_net / q_in if q_in > 0 else 0.0
                st.metric(t.get("heat_in", "Calore In"), f"{q_in:.1f} kJ/kg")
                st.metric(t.get("heat_out", "Calore Out"), f"{q_out:.1f} kJ/kg")
                st.metric(t.get("net_work", "Lavoro Netto"), f"{l_net:.1f} kJ/kg")
                st.metric(t.get("efficiency", "Rendimento"), f"{eta_cycle:.2f} %")

        with col_plot:
            st.subheader(t.get("plots", "Diagrammi"))
            tab_ts, tab_pv, tab_tv, tab_hs = st.tabs(["T-s", "P-v", "T-v", "h-s"])
            with tab_ts:
                fig = plotly_base("T-s Diagram", "s (kJ/kgK)", "T (°C)", THEME)
                add_steam_dome(fig, "s", "T")
                add_steam_points(fig, closed_points, "s", "T", "Cycle", THEME["gold"])
                st.plotly_chart(fig, use_container_width=True)
            with tab_pv:
                fig = plotly_base("P-v Diagram", "v (m³/kg)", "P (bar)", THEME, xlog=True, ylog=True)
                add_steam_dome(fig, "v", "P")
                add_steam_points(fig, closed_points, "v", "P", "Cycle", THEME["cyan"])
                st.plotly_chart(fig, use_container_width=True)
            with tab_tv:
                fig = plotly_base("T-v Diagram", "v (m³/kg)", "T (°C)", THEME, xlog=True)
                add_steam_dome(fig, "v", "T")
                add_steam_points(fig, closed_points, "v", "T", "Cycle", THEME["green"])
                st.plotly_chart(fig, use_container_width=True)
            with tab_hs:
                fig = plotly_base("h-s Diagram", "s (kJ/kgK)", "h (kJ/kg)", THEME)
                add_steam_dome(fig, "s", "h")
                add_steam_points(fig, closed_points, "s", "h", "Cycle", THEME["red"])
                st.plotly_chart(fig, use_container_width=True)
    else:
        st.write("Add points from the sidebar to start building your cycle.")
