import matplotlib.patches as patches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
from iapws import IAPWS97
import io
from matplotlib.backends.backend_pdf import PdfPages


def create_pdf_report(cycle_name, report_text, points_df, fig_ts):
    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        # Page 1: Report Title and Text Analysis
        fig_rep = plt.figure(figsize=(8.27, 11.69)) # A4
        plt.axis('off')
        plt.text(0.1, 0.95, f"THERMODYNAMIC ANALYSIS REPORT: {cycle_name.upper()}", 
                 fontsize=14, fontweight='bold', family='monospace')
        plt.text(0.1, 0.1, report_text, fontsize=9, family='monospace', verticalalignment='top')
        plt.text(0.1, 0.05, "Generated by Thermodynamic CAD Web - Educational Suite", 
                 fontsize=8, fontstyle='italic')
        pdf.savefig(fig_rep)
        plt.close(fig_rep)
        
        # Page 2: State Point Table
        fig_tab, ax_tab = plt.subplots(figsize=(8.27, 4))
        ax_tab.axis('off')
        the_table = ax_tab.table(cellText=points_df.values, colLabels=points_df.columns, 
                                 loc='center', cellLoc='center')
        the_table.auto_set_font_size(False)
        the_table.set_fontsize(8)
        the_table.scale(1.2, 1.2)
        plt.title("State Point Table", fontsize=12, fontweight='bold')
        pdf.savefig(fig_tab)
        plt.close(fig_tab)
        
        # Page 3: T-s Diagram (Matplotlib version for PDF)
        # Note: We can't easily export Plotly to PDF without extra libs like kaleido,
        # so we stay with a high-quality matplotlib T-s representation.
        if "pts" in st.session_state:
            fig_plt, ax_plt = plt.subplots(figsize=(8, 6))
            # ... simple plot placeholder for now or re-use existing schematics ...
            plt.title(f"{cycle_name} - T-s Diagram", fontsize=12)
            pdf.savefig(fig_plt)
            plt.close(fig_plt)
            
    buf.seek(0)
    return buf
from streamlit_javascript import st_javascript

st.set_page_config(page_title="TermoWeb UI", page_icon="⚡", layout="wide")

THEME = {
    "bg": "#0d141b",
    "panel": "#10202c",
    "grid": "rgba(184, 219, 237, 0.14)",
    "text": "#e7f6ff",
    "cyan": "#50c8e8",
    "gold": "#ffd166",
    "orange": "#ff9f43",
    "red": "#ff6b6b",
    "blue": "#74c0fc",
    "green": "#4dd4ac",
    "gray": "#9aa7b2",
}

st.markdown(
    """
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
    
    .block-container { padding-top: 1rem; padding-bottom: 2rem; max-width: 1550px; }
    
    .stApp {
        background: 
            radial-gradient(circle at 2% 2%, rgba(80, 200, 232, 0.12), transparent 25%),
            radial-gradient(circle at 98% 98%, rgba(255, 159, 67, 0.08), transparent 25%),
            linear-gradient(180deg, #050b10 0%, #0a141d 100%);
        color: #e2f2ff;
        font-family: 'Inter', sans-serif;
    }

    /* Glassmorphism Panels */
    .hero {
        margin-bottom: 1.5rem; padding: 1.8rem 2.2rem;
        border-radius: 24px; 
        background: linear-gradient(135deg, rgba(13, 28, 41, 0.92), rgba(18, 52, 77, 0.85));
        border: 1px solid rgba(80, 200, 232, 0.25);
        box-shadow: 0 20px 50px rgba(0, 0, 0, 0.4);
        backdrop-filter: blur(10px);
    }
    .hero h1 { 
        margin: 0; 
        background: linear-gradient(90deg, #8ae8ff, #ffffff);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-size: 2.8rem; font-weight: 700; line-height: 1.1; 
    }
    .hero p { margin: 0.8rem 0 0 0; color: #b0d4e3; font-size: 1.1rem; }
    .authorline { font-size: 0.9rem; opacity: 0.8; margin-top: 0.5rem; color: #50c8e8; }

    /* CAD Report Style */
    .cad-report {
        font-family: 'JetBrains Mono', 'Consolas', monospace;
        background: #060c12;
        border: 1px solid rgba(80, 200, 232, 0.15);
        border-radius: 12px;
        padding: 1.2rem;
        color: #92e1ff;
        line-height: 1.5;
        font-size: 0.88rem;
        overflow-x: auto;
    }

    /* Metrics Styling */
    div[data-testid="stMetric"] {
        background: rgba(16, 32, 46, 0.6);
        border: 1px solid rgba(80, 200, 232, 0.2);
        border-radius: 16px; padding: 0.8rem;
        backdrop-filter: blur(5px);
        transition: transform 0.2s ease;
    }
    div[data-testid="stMetric"]:hover { transform: translateY(-2px); border-color: rgba(80, 200, 232, 0.4); }

    /* Tabs Styling */
    .stTabs [data-baseweb="tab-list"] { gap: 0.5rem; background: transparent; }
    .stTabs [data-baseweb="tab"] {
        border-radius: 10px 10px 0 0;
        background: rgba(13, 28, 41, 0.5);
        border: 1px solid rgba(80, 200, 232, 0.1);
        padding: 0.5rem 1.2rem;
        color: #9aa7b2;
    }
    .stTabs [aria-selected="true"] {
        background: rgba(80, 200, 232, 0.15) !important;
        border-color: #50c8e8 !important;
        color: #ffffff !important;
    }

    /* Input Fields */
    .stNumberInput input, .stTextInput input {
        background: rgba(7, 18, 27, 0.8) !important;
        border: 1px solid rgba(80, 200, 232, 0.2) !important;
        color: white !important;
    }
    
    /* Sidebar */
    section[data-testid="stSidebar"] {
        background-color: #071018;
        border-right: 1px solid rgba(80, 200, 232, 0.1);
    }
    </style>
    """,
    unsafe_allow_html=True,
)


def get_browser_lang():
    # Attempt to detect language, default to 'it'
    return "it"


if "app_lang" not in st.session_state:
    st.session_state["app_lang"] = "it"
if "cad_points" not in st.session_state:
    st.session_state["cad_points"] = []
if "cad_close_cycle" not in st.session_state:
    st.session_state["cad_close_cycle"] = True


dict_t = {
    "en": {
        "main_title": "Thermodynamic CAD Web",
        "subtitle": "Professional engineering suite for ideal and real cycles with high-fidelity analytics.",
        "author": "Created by Prof. Ing. Andrea Viola | Educational CAD Suite",
        "sidebar_head": "Cycles & Settings",
        "select_cycle": "Select thermodynamic cycle",
        "inputs": "Design Parameters",
        "results": "Analysis Report",
        "plots": "Engineering Diagrams",
        "net_work": "Net Output",
        "efficiency": "Thermal Efficiency",
        "heat_in": "Energy Input",
        "heat_out": "Energy Rejection",
        "pmax": "Peak Pressure",
        "comp_ratio": "Compr. Ratio r",
        "k_exp": "Exp. Exponent k",
        "eta_is": "Isentropic η",
        "ideal": "Isentropic Process",
        "real": "Polytropic/Real Process",
        "bwr": "Back Work Ratio",
        "p_evap": "Evaporator P (bar)",
        "p_cond": "Condenser P (bar)",
        "t_max": "Max Temperature (°C)",
        "build_info": "Free-form construction of complex cycles with multi-phase support.",
        "points": "State Point Table",
        "stats": "Energy Balance",
    },
    "it": {
        "main_title": "CAD Termodinamico Web",
        "subtitle": "Suite professionale per lo studio dei cicli ideali e reali con analisi ad alta fedeltà.",
        "author": "Creato dal Prof. Ing. Andrea Viola | Progetto Didattico Open Source",
        "sidebar_head": "Cicli e Impostazioni",
        "select_cycle": "Seleziona ciclo termodinamico",
        "inputs": "Parametri di Progetto",
        "results": "Report Analisi",
        "plots": "Diagrammi Ingegneristici",
        "net_work": "Lavoro Netto",
        "efficiency": "Rendimento Termico",
        "heat_in": "Calore Introdotto",
        "heat_out": "Calore Ceduto",
        "pmax": "Pressione Max",
        "comp_ratio": "Rapp. Compressione r",
        "k_exp": "Esponente k",
        "eta_is": "η Isentropico",
        "ideal": "Processo Ideale",
        "real": "Processo Reale",
        "bwr": "Back Work Ratio",
        "p_evap": "Pressione Evap. (bar)",
        "p_cond": "Pressione Cond. (bar)",
        "t_max": "Temperatura Max (°C)",
        "build_info": "Costruzione libera di cicli complessi con supporto multi-fase.",
        "points": "Tabella Punti di Stato",
        "stats": "Bilancio Energetico",
    },
}

with st.sidebar:
    st.title("🌐 Language")
    lang_choice = st.radio("", ["Italiano", "English"], 
                           index=0 if st.session_state["app_lang"] == "it" else 1,
                           horizontal=True)
    lang = "it" if "Italiano" in lang_choice else "en"
    st.session_state["app_lang"] = lang
    t = dict_t[lang]

st.markdown(
    f"""
    <div class="hero">
        <h1>{t['main_title']}</h1>
        <p>{t['subtitle']}</p>
        <div class="authorline">{t['author']}</div>
    </div>
    """,
    unsafe_allow_html=True,
)

st.divider()


def get_iapws_robust(**args):
    try:
        return IAPWS97(**args)
    except Exception:
        return None


def quality_label(x):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "n/d"
    if 0.0 < x < 1.0:
        return f"{x:.3f}"
    if x <= 0.0:
        return "liq. sat."
    if x >= 1.0:
        return "vap. sat."
    return f"{x:.3f}"


def steam_point(name, state):
    return {"name": name, "P": state.P * 10.0, "T": state.T - 273.15, "h": state.h, "s": state.s, "v": state.v, "x": state.x}


@st.cache_data(show_spinner=False)
def build_steam_dome():
    pressures = np.logspace(np.log10(0.001), np.log10(22.0), 160)
    sat_f = {"P": [], "T": [], "v": [], "h": [], "s": []}
    sat_g = {"P": [], "T": [], "v": [], "h": [], "s": []}
    for p in pressures:
        try:
            st_f = IAPWS97(P=p, x=0)
            sat_f["P"].append(st_f.P * 10.0); sat_f["T"].append(st_f.T - 273.15); sat_f["v"].append(st_f.v); sat_f["h"].append(st_f.h); sat_f["s"].append(st_f.s)
        except Exception:
            pass
        try:
            st_g = IAPWS97(P=p, x=1)
            sat_g["P"].append(st_g.P * 10.0); sat_g["T"].append(st_g.T - 273.15); sat_g["v"].append(st_g.v); sat_g["h"].append(st_g.h); sat_g["s"].append(st_g.s)
        except Exception:
            pass
    return sat_f, sat_g


def plotly_base(title, x_title, y_title, xlog=False, ylog=False, height=460):
    fig = go.Figure()
    fig.update_layout(
        title=title,
        height=height,
        paper_bgcolor=THEME["bg"],
        plot_bgcolor=THEME["panel"],
        font=dict(color=THEME["text"]),
        margin=dict(l=20, r=20, t=52, b=20),
        legend=dict(bgcolor="rgba(6, 19, 27, 0.78)", bordercolor="rgba(80, 200, 232, 0.18)", borderwidth=1),
        hoverlabel=dict(bgcolor="#06131b", bordercolor=THEME["cyan"], font=dict(color=THEME["text"])),
    )
    fig.update_xaxes(title=x_title, showgrid=True, gridcolor=THEME["grid"], zeroline=False, type="log" if xlog else "linear")
    fig.update_yaxes(title=y_title, showgrid=True, gridcolor=THEME["grid"], zeroline=False, type="log" if ylog else "linear")
    return fig


def add_line(fig, x, y, name, color, dash="solid", width=3):
    fig.add_trace(go.Scatter(x=x, y=y, mode="lines", name=name, line=dict(color=color, width=width, dash=dash), hoverinfo="skip"))


def add_steam_points(fig, points, x_key, y_key, name, color):
    customdata = [[p["name"], p["P"], p["T"], p["h"], p["s"], p["v"], quality_label(p.get("x"))] for p in points]
    fig.add_trace(
        go.Scatter(
            x=[p[x_key] for p in points],
            y=[p[y_key] for p in points],
            mode="lines+markers+text",
            name=name,
            text=[p["name"] for p in points],
            textposition="top center",
            line=dict(color=color, width=3),
            marker=dict(size=10, color=color, line=dict(color="#17303b", width=2)),
            customdata=customdata,
            hovertemplate="<b>%{customdata[0]}</b><br>P = %{customdata[1]:.3f} bar<br>T = %{customdata[2]:.2f} °C<br>h = %{customdata[3]:.2f} kJ/kg<br>s = %{customdata[4]:.4f} kJ/kgK<br>v = %{customdata[5]:.5e} m³/kg<br>x = %{customdata[6]}<extra></extra>",
        )
    )


def add_generic_points(fig, points, x_key, y_key, name, color):
    customdata = [[p["name"], p["P"], p["T"], p["h"], p["s"], p["v"]] for p in points]
    fig.add_trace(
        go.Scatter(
            x=[p[x_key] for p in points],
            y=[p[y_key] for p in points],
            mode="lines+markers+text",
            name=name,
            text=[p["name"] for p in points],
            textposition="top center",
            line=dict(color=color, width=3),
            marker=dict(size=10, color=color, line=dict(color="#17303b", width=2)),
            customdata=customdata,
            hovertemplate="<b>%{customdata[0]}</b><br>P = %{customdata[1]:.3f} bar<br>T = %{customdata[2]:.2f} °C<br>h = %{customdata[3]:.2f} kJ/kg<br>s = %{customdata[4]:.4f} kJ/kgK<br>v = %{customdata[5]:.5e} m³/kg<extra></extra>",
        )
    )


def add_steam_dome(fig, x_key, y_key):
    sat_f, sat_g = build_steam_dome()
    add_line(fig, sat_f[x_key], sat_f[y_key], "Liquido saturo", THEME["cyan"], width=2)
    add_line(fig, sat_g[x_key], sat_g[y_key], "Vapore saturo", THEME["cyan"], width=2)


def draw_rankine_schema(p1, p2, p3, p4):
    fig_s, ax = plt.subplots(figsize=(6, 5))
    ax.set_facecolor("#10202c"); ax.axis("off"); ax.set_xlim(0, 10.5); ax.set_ylim(-2, 11)
    ax.add_patch(patches.Rectangle((1.5, 3.5), 2.5, 4.5, fill=True, color="#2c1e1e", ec=THEME["red"], lw=2))
    ax.add_patch(patches.Polygon([(6.5, 7.5), (7.8, 6.8), (7.8, 4.2), (6.5, 3.5)], fill=True, color="#2f2214", ec=THEME["orange"], lw=2))
    ax.add_patch(patches.Circle((7.15, 1.5), 0.8, fill=True, color="#1a2433", ec=THEME["blue"], lw=2))
    ax.add_patch(patches.Circle((4, 0.5), 0.5, fill=True, color="#1a3333", ec=THEME["cyan"], lw=2))
    ax.text(2.75, 5.75, "Caldaia", color=THEME["red"], ha="center", va="center", weight="bold")
    ax.text(7.15, 8.2, "Turbina", color=THEME["orange"], ha="center", weight="bold")
    ax.text(8.8, 1.5, "Condensatore", color=THEME["blue"], ha="center", va="center", weight="bold")
    ax.text(4, 1.5, "Pompa", color=THEME["cyan"], ha="center", weight="bold")
    ax.plot([3.5, 2.75, 2.75], [0.5, 0.5, 3.5], color=THEME["cyan"], lw=2)
    ax.plot([2.75, 2.75, 6.5, 6.5], [8.0, 9.5, 9.5, 7.5], color=THEME["red"], lw=2)
    ax.plot([7.15, 7.15], [5.5, 2.3], color=THEME["orange"], lw=2)
    ax.plot([6.35, 4.5, 4.5, 4.0], [1.5, 1.5, 0.5, 0.5], color=THEME["blue"], lw=2)
    for x, y, lbl, p in [(4.5, 0.5, "1", p1), (2.75, 2.0, "2", p2), (4.5, 9.7, "3", p3), (7.3, 3.5, "4", p4)]:
        ax.text(x, y, f"[{lbl}]\\nP:{p.P*10:.2f} bar\\nT:{p.T-273.15:.1f} °C", color="white", fontsize=7, bbox=dict(boxstyle="round,pad=0.2", fc="#10202c", ec="white", alpha=0.7))
    return fig_s


def draw_brayton_schema(p1, p2, p3, p4):
    fig_s, ax = plt.subplots(figsize=(6, 5))
    ax.set_facecolor("#10202c"); ax.axis("off"); ax.set_xlim(0, 1); ax.set_ylim(0, 1)
    ax.plot([0.3, 0.9], [0.4, 0.4], color="gray", linewidth=4, zorder=1); ax.text(0.6, 0.35, "Albero", color="white", weight="bold", ha="center", fontsize=9)
    ax.plot([0.35, 0.35, 0.45], [0.5, 0.8, 0.8], color="#555555", linewidth=10, zorder=1); ax.plot([0.55, 0.65, 0.65], [0.8, 0.8, 0.5], color="#555555", linewidth=10, zorder=1)
    ax.add_patch(patches.Polygon([[0.2, 0.3], [0.2, 0.7], [0.4, 0.6], [0.4, 0.4]], closed=True, color="#2196F3", zorder=2))
    ax.add_patch(patches.Polygon([[0.6, 0.4], [0.6, 0.6], [0.8, 0.7], [0.8, 0.3]], closed=True, color="#4CAF50", zorder=2))
    ax.add_patch(patches.Rectangle((0.4, 0.7), 0.2, 0.2, color="#FFCA28", zorder=2))
    ax.text(0.3, 0.5, "Compressore", color="white", weight="bold", ha="center", va="center", rotation=90, fontsize=8)
    ax.text(0.7, 0.5, "Turbina", color="white", weight="bold", ha="center", va="center", rotation=-90, fontsize=8)
    ax.text(0.5, 0.8, "Combustore", color="black", weight="bold", ha="center", va="center", fontsize=8)
    for x, y, lbl, p in [(0.1, 0.5, "1", p1), (0.35, 0.9, "2", p2), (0.65, 0.9, "3", p3), (0.9, 0.5, "4", p4)]:
        ax.text(x, y, f"{lbl}\\nP:{p['P']:.1f} bar\\nT:{p['T']:.0f} °C", color="white", fontsize=7, bbox=dict(boxstyle="round,pad=0.2", fc="#10202c", ec="white", alpha=0.7))
    return fig_s


def draw_otto_diesel_schema(is_diesel=False):
    fig_s, ax = plt.subplots(figsize=(6, 4))
    ax.set_facecolor("#10202c"); ax.axis("off")
    ax.add_patch(patches.Rectangle((0.3, 0.2), 0.4, 0.6, fill=False, color="white", lw=3))
    piston_y = 0.3 if is_diesel else 0.4
    ax.add_patch(patches.Rectangle((0.3, piston_y), 0.4, 0.1, color="gray"))
    ax.plot([0.5, 0.5], [piston_y, 0.05], color="gray", lw=5)
    ax.text(0.5, 0.9, "Diesel" if is_diesel else "Otto", color="white", ha="center", weight="bold")
    return fig_s


def render_point_table(points):
    df = pd.DataFrame(points)
    cols = [c for c in ["name", "P", "T", "h", "s", "v", "x"] if c in df.columns]
    st.dataframe(df[cols], use_container_width=True, hide_index=True)


cycle_options = [
    "💧 Acqua & Vapore (CAD)",
    "🔥 Brayton (CAD)",
    "⚙️ Ciclo Otto",
    "🛢️ Ciclo Diesel",
    "❄️ Frigorifero",
    "🎨 Laboratorio Aria (CAD)"
]
st.sidebar.header(t["sidebar_head"])
ciclo = st.sidebar.radio(t["select_cycle"], cycle_options)

def download_report_btn(name, report, df, key):
    pdf_buf = create_pdf_report(name, report, df, None)
    st.download_button(label=f"📥 Scarica Report PDF ({name})", 
                       data=pdf_buf, 
                       file_name=f"Report_{name.replace(' ','_')}.pdf",
                       mime="application/pdf",
                       key=key)


if "water_pts" not in st.session_state:
    st.session_state["water_pts"] = []
if "water_components" not in st.session_state:
    st.session_state["water_components"] = []
if "water_portata" not in st.session_state:
    st.session_state["water_portata"] = 100.0


def add_water_pt(name, **args):
    state = get_iapws_robust(**args)
    if state:
        st.session_state["water_pts"].append(steam_point(name, state))
        return True
    return False


if "Acqua" in ciclo:
    st.header("💧 Water Cycle & Rankine CAD")
    
    col_in, col_main = st.columns([1, 2.5], gap="large")
    
    with col_in:
        st.subheader("1. ➕ Add State Point")
        p_mode = st.selectbox("Property Mask", ["P-T", "P-x", "P-s", "P-h", "T-x"], key="w_p_mode")
        v1 = st.number_input("Value 1", value=50.0, format="%.3f", key="w_v1")
        v2 = st.number_input("Value 2", value=450.0, format="%.3f", key="w_v2")
        p_name = st.text_input("Point Name", value=f"P{len(st.session_state['water_pts'])+1}", key="w_name")
        
        if st.button("Add Point", use_container_width=True):
            args = {}
            if p_mode == "P-T": args = {"P": v1/10.0, "T": v2+273.15}
            elif p_mode == "P-x": args = {"P": v1/10.0, "x": v2}
            elif p_mode == "P-s": args = {"P": v1/10.0, "s": v2}
            elif p_mode == "P-h": args = {"P": v1/10.0, "h": v2}
            elif p_mode == "T-x": args = {"T": v1+273.15, "x": v2}
            
            if add_water_pt(p_name, **args): st.rerun()
            else: st.error("Invalid thermodynamic state.")

        st.divider()
        st.subheader("2. ⚙️ Define Component")
        if len(st.session_state["water_pts"]) >= 2:
            p_names = [p["name"] for p in st.session_state["water_pts"]]
            c_type = st.selectbox("Type", ["Turbina", "Pompa", "Caldaia/Risur.", "Condensatore", "Mixer/FWH"], key="w_c_type")
            c_in = st.selectbox("Inlet", p_names, key="w_c_in")
            c_out = st.selectbox("Outlet", p_names, key="w_c_out")
            c_y = st.number_input("Mass Fraction (y)", value=1.0, step=0.01, key="w_c_y")
            
            if st.button("Add Component", use_container_width=True):
                st.session_state["water_components"].append({"type": c_type, "in": c_in, "out": c_out, "y": c_y})
                st.rerun()
        else:
            st.info("Add at least 2 points to define components.")

        st.divider()
        st.subheader("3. 📋 Global Parameters")
        st.session_state["water_portata"] = st.number_input("Global Mass Flow (kg/s)", value=st.session_state["water_portata"])
        
        if st.button("Reset Cycle", type="primary", use_container_width=True):
            st.session_state["water_pts"] = []
            st.session_state["water_components"] = []
            st.rerun()

    # --- Calculations ---
    w_pts = st.session_state["water_pts"]
    w_comp = st.session_state["water_components"]
    
    l_t = l_p = q_in = q_out = 0.0
    
    def get_pt(name): return next((p for p in w_pts if p["name"] == name), None)
    
    comp_details = []
    for c in w_comp:
        pt1, pt2 = get_pt(c["in"]), get_pt(c["out"])
        if not pt1 or not pt2: continue
        
        dh = pt2["h"] - pt1["h"]
        y = c["y"]
        if c["type"] == "Turbina": l_t += abs(dh) * y
        elif c["type"] == "Pompa": l_p += abs(dh) * y
        elif c["type"] == "Caldaia/Risur.": q_in += dh * y
        elif c["type"] == "Condensatore": q_out += abs(dh) * y
        
        comp_details.append(f"  {c['type']:<15} : {c['in']} ➜ {c['out']} | y={y:.3f} | Δh={dh:>8.2f} kJ/kg")

    l_net = l_t - l_p
    eta_cycle = (l_net / q_in) * 100 if q_in > 0 else 0
    p_net = l_net * st.session_state["water_portata"]

    with col_main:
        m1, m2, m3 = st.columns(3)
        m1.metric("Lavoro Netto", f"{l_net:.2f} kJ/kg")
        m2.metric("Rendimento", f"{eta_cycle:.2f} %")
        m3.metric("Potenza Netta", f"{p_net/1000:.2f} MW")
        
        tab_list, tab_ts, tab_pv, tab_hs, tab_rep = st.tabs(["State Points", "T-s Diagram", "P-v Diagram", "h-s Diagram", "Analysis Report"])
        
        with tab_list:
            render_point_table(w_pts)
            st.subheader("Defined Components")
            for i, c in enumerate(w_comp):
                c_col1, c_col2 = st.columns([4, 1])
                c_col1.write(f"**{c['type']}**: {c['in']} ➜ {c['out']} (y={c['y']})")
                if c_col2.button("🗑️", key=f"del_c_{i}"):
                    st.session_state["water_components"].pop(i)
                    st.rerun()

        with tab_ts:
            fig = plotly_base("Diagramma T-s (Acqua/Vapore)", "s (kJ/kgK)", "T (°C)")
            add_steam_dome(fig, "s", "T")
            if w_pts: add_steam_points(fig, w_pts, "s", "T", "Punti di Stato", THEME["gold"])
            # Close cycle for visualization if multiple points
            if len(w_pts) > 2 and st.session_state["cad_close_cycle"]:
                path_pts = w_pts + [w_pts[0]]
                add_line(fig, [p["s"] for p in path_pts], [p["T"] for p in path_pts], "Percorso", THEME["cyan"], dash="dot", width=1)
            st.plotly_chart(fig, use_container_width=True)

        with tab_pv:
            fig = plotly_base("Diagramma P-v", "v (m³/kg)", "P (bar)", xlog=True, ylog=True)
            add_steam_dome(fig, "v", "P")
            if w_pts: add_steam_points(fig, w_pts, "v", "P", "Punti di Stato", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)
            
        with tab_hs:
            fig = plotly_base("Diagramma Mollier h-s", "s (kJ/kgK)", "h (kJ/kg)")
            add_steam_dome(fig, "s", "h")
            if w_pts: add_steam_points(fig, w_pts, "s", "h", "Punti di Stato", THEME["red"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_rep:
            comp_txt = "\n".join(comp_details) if comp_details else "  (Nessun componente definito)"
            rep = f"""
════════════════════════════════════════════════════════════
             REPORT ANALISI CICLO H2O (CAD)
════════════════════════════════════════════════════════════

-- ANALISI COMPONENTI --------------------------------------
{comp_txt}

-- BILANCIO ENERGETICO -------------------------------------
   Lavoro Turbina:   {l_t:>8.2f} kJ/kg
   Lavoro Pompa:     {l_p:>8.2f} kJ/kg
   Calore Intro:     {q_in:>8.2f} kJ/kg
   Calore Ceduto:    {q_out:>8.2f} kJ/kg

-- PRESTAZIONI GLOBALI -------------------------------------
   LAVORO NETTO:     {l_net:>8.2f} kJ/kg
   POTENZA NETTA:    {p_net/1000:>8.3f} MW
   REND. CICLO:      {eta_cycle:>8.2f} %
   Portata ṁ:        {st.session_state['water_portata']:>8.2f} kg/s
════════════════════════════════════════════════════════════
            """
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Acqua", rep, pd.DataFrame(w_pts), "pdf_w")



elif "Brayton" in ciclo:
    st.header("🔥 Brayton – Gas Turbine CAD")
    
    col_in, col_main = st.columns([1, 2.5], gap="large")
    
    with col_in:
        st.subheader(t["inputs"])
        with st.expander("A. Compression & Ambient", expanded=True):
            p1 = st.number_input("P1 (bar)", value=1.013, format="%.3f")
            t1 = st.number_input("T1 (°C)", value=15.0)
            p2 = st.number_input("P2 (bar)", value=12.0)
            cpa = st.number_input("cp_air (kJ/kgK)", value=1.005, format="%.3f")
            ka = st.number_input("k_air", value=1.40, format="%.2f")
            eta_ic = st.number_input("η_is Compressor", value=0.85, step=0.01)
            
        with st.expander("B. Combustion & Fuel", expanded=True):
            t3 = st.number_input("T3 Max (°C)", value=1100.0)
            hi = st.number_input("Hi Fuel (kJ/kg)", value=42000.0, step=100.0)
            eta_cc = st.number_input("η_combustor", value=0.98, step=0.01)
            cpg_comb = st.number_input("cp_gas (comb)", value=1.15, format="%.3f")
            a0 = st.number_input("Stoich. Air (a0)", value=14.7, format="%.1f")
            
        with st.expander("C. Expansion & Mechanical", expanded=True):
            p4 = st.number_input("P4 Exit (bar)", value=1.013, format="%.3f")
            eta_it = st.number_input("η_is Turbine", value=0.88, step=0.01)
            cpg_esp = st.number_input("cp_gas (exp)", value=1.10, format="%.3f")
            kg = st.number_input("k_gas", value=1.33, format="%.2f")
            eta_m = st.number_input("η_mechanical", value=0.99, step=0.01)
            m_dot = st.number_input("Air Flow ṁ (kg/s)", value=50.0)

    # --- Calculations ---
    t1k, t3k = t1 + 273.15, t3 + 273.15
    # Compression
    t2sk = t1k * ((p2 / p1) ** ((ka - 1) / ka))
    t2rk = t1k + (t2sk - t1k) / eta_ic
    l_tc = cpa * (t2sk - t1k)
    l_ic = cpa * (t2rk - t1k)
    p_ic = m_dot * l_ic
    p_ac = p_ic / eta_m
    
    # Combustion
    g_c = m_dot * cpg_comb * (t3k - t2rk) / (eta_cc * hi)
    m_gas = m_dot + g_c
    ac_real = m_dot / g_c
    excess_air = (ac_real / a0 - 1) * 100
    
    # Expansion
    t4sk = t3k * ((p4 / p2) ** ((kg - 1) / kg))
    t4rk = t3k - eta_it * (t3k - t4sk)
    l_it = cpg_esp * (t3k - t4rk)
    p_it = m_gas * l_it
    p_e_lorda = p_it * eta_m
    
    # Bottom Line
    p_e_netta = p_e_lorda - p_ac
    q_in = g_c * eta_cc * hi
    eta_te = (p_e_netta / q_in) * 100 if q_in > 0 else 0
    bwr = (p_ac / p_e_lorda) * 100 if p_e_lorda > 0 else 0
    cons_spec = (g_c * 3600) / p_e_netta if p_e_netta > 0 else 0 # kg/kWh

    # --- Data Points for Plot ---
    def ent_air(tk, pb): return cpa * np.log(tk/288.15) - 0.287 * np.log(pb/1.013)
    def ent_gas(tk, pb): return cpg_esp * np.log(tk/288.15) - (0.287*0.95) * np.log(pb/1.013)
    
    pts = [
        {"name": "1", "P": p1, "T": t1, "h": cpa*t1k, "s": ent_air(t1k, p1), "v": 0.287*t1k/(p1*100)},
        {"name": "2", "P": p2, "T": t2rk-273.15, "h": cpa*t2rk, "s": ent_air(t2rk, p2), "v": 0.287*t2rk/(p2*100)},
        {"name": "3", "P": p2, "T": t3, "h": cpg_esp*t3k, "s": ent_gas(t3k, p2), "v": 0.287*t3k/(p2*100)},
        {"name": "4", "P": p4, "T": t4rk-273.15, "h": cpg_esp*t4rk, "s": ent_gas(t4rk, p4), "v": 0.287*t4rk/(p4*100)},
        {"name": "1", "P": p1, "T": t1, "h": cpa*t1k, "s": ent_air(t1k, p1), "v": 0.287*t1k/(p1*100)},
    ]

    with col_main:
        m1, m2, m3 = st.columns(3)
        m1.metric(t["net_work"], f"{p_e_netta/1000:.2f} MW")
        m2.metric(t["efficiency"], f"{eta_te:.2f} %")
        m3.metric(t["bwr"], f"{bwr:.1f} %")
        
        tab_flow, tab_ts, tab_pv, tab_hs = st.tabs(["Schema Impianto", "T-s Diagram", "P-v Diagram", "Analysis Report"])
        
        with tab_flow:
            st.pyplot(draw_brayton_schema(pts[0], pts[1], pts[2], pts[3]))
        
        with tab_ts:
            fig = plotly_base("Diagramma Termodinamico T-s", "s (kJ/kgK)", "T (°C)")
            add_generic_points(fig, pts, "s", "T", "Ciclo Reale", THEME["orange"])
            st.plotly_chart(fig, use_container_width=True)
            
        with tab_pv:
            fig = plotly_base("Diagramma Termodinamico P-v", "v (m³/kg)", "P (bar)", xlog=True)
            add_generic_points(fig, pts, "v", "P", "Ciclo Reale", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)

        with tab_hs:
            # Reusing the tab for the text report matching desktop app
            rep = f"""
════════════════════════════════════════════════════════════
             REPORT ANALISI CICLO BRAYTON
════════════════════════════════════════════════════════════

-- A. COMPRESSIONE -----------------------------------------
   T2 ideale:    {t2sk-273.15:>8.2f} °C
   T2 reale:     {t2rk-273.15:>8.2f} °C
   Lav. isent.:  {l_tc:>8.2f} kJ/kg
   Lav. interno: {l_ic:>8.2f} kJ/kg
   Potenza asse: {p_ac/1000:>8.3f} MW

-- B. COMBUSTIONE ------------------------------------------
   Portata comb: {g_c:>8.4f} kg/s
   Ecc. Aria:    {excess_air:>8.2f} %
   Calore intro: {q_in/1000:>8.3f} MW

-- C. ESPANSIONE -------------------------------------------
   T4 ideale:    {t4sk-273.15:>8.2f} °C
   T4 reale:     {t4rk-273.15:>8.2f} °C
   Lav. interno: {l_it:>8.2f} kJ/kg
   Pot. lorda:   {p_e_lorda/1000:>8.3f} MW

-- D. PRESTAZIONI GLOBALI ----------------------------------
   POT. NETTA:   {p_e_netta/1000:>8.3f} MW
   REND. EFF.:   {eta_te:>8.2f} %
   BWR:          {bwr:>8.2f} %
   CONS. SPEC.:  {cons_spec:>8.4f} kg/kWh
════════════════════════════════════════════════════════════
            """
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Brayton", rep, pd.DataFrame(pts), "pdf_b")



elif "Otto" in ciclo:
    st.header("⚙️ Otto Cycle Engine CAD")
    col_in, col_main = st.columns([1, 2.5], gap="large")
    
    with col_in:
        st.subheader(t["inputs"])
        p1 = st.number_input("P1 Intake (bar)", value=1.0)
        t1 = st.number_input("T1 Intake (°C)", value=25.0)
        r = st.number_input("Compression Ratio r", value=9.0)
        t3 = st.number_input("T3 Peak (°C)", value=1200.0)
        k = st.number_input("k (exp.)", value=1.4)
        cv = st.number_input("cv (kJ/kgK)", value=0.718)
        eta = st.number_input("η isentropic", value=0.85)

    rg = cv * (k - 1)
    t1k, t3k = t1 + 273.15, t3 + 273.15
    v1 = rg * t1k / (p1 * 100)
    v2 = v1 / r
    t2sk = t1k * (r ** (k - 1))
    t2k = t1k + (t2sk - t1k) / eta
    p2 = p1 * (t2k / t1k) * (v1 / v2)
    p3 = p2 * (t3k / t2k)
    t4sk = t3k * ((1 / r) ** (k - 1))
    t4k = t3k - eta * (t3k - t4sk)
    p4 = p3 * (t4k / t3k) * (v2 / v1)

    pts = [
        {"name": "1", "P": p1, "T": t1, "h": cv*t1k, "s": cv*np.log(t1k/273.15), "v": v1},
        {"name": "2", "P": p2, "T": t2k-273.15, "h": cv*t2k, "s": cv*np.log(t2k/273.15)+rg*np.log(v2/v1), "v": v2},
        {"name": "3", "P": p3, "T": t3, "h": cv*t3k, "s": cv*np.log(t3k/273.15)+rg*np.log(v2/v1), "v": v2},
        {"name": "4", "P": p4, "T": t4k-273.15, "h": cv*t4k, "s": cv*np.log(t4k/273.15), "v": v1},
        {"name": "1", "P": p1, "T": t1, "h": cv*t1k, "s": cv*np.log(t1k/273.15), "v": v1},
    ]
    q_in = cv * (t3k - t2k)
    q_out = cv * (t4k - t1k)
    w_net = q_in - q_out
    eta_cycle = 100.0 * w_net / q_in if q_in > 0 else 0

    with col_main:
        m1, m2, m3 = st.columns(3)
        m1.metric("Lavoro Netto", f"{w_net:.1f} kJ/kg")
        m2.metric("Rendimento", f"{eta_cycle:.2f} %")
        m3.metric("Pressione Max", f"{p3:.2f} bar")
        
        tab_flow, tab_pv, tab_ts, tab_rep = st.tabs(["Schema Motore", "P-v Diagram", "T-s Diagram", "Analysis Report"])
        with tab_flow: st.pyplot(draw_otto_diesel_schema(False))
        with tab_pv:
            fig = plotly_base("Diagramma P-v", "v (m³/kg)", "P (bar)")
            add_line(fig, np.linspace(v2, v1, 60), p1 * (v1 / np.linspace(v2, v1, 60)) ** k, "Isentropica", THEME["gray"], dash="dash")
            add_generic_points(fig, pts, "v", "P", "Ciclo Otto", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)
            rep = f"PEAK PRESSURE: {p3:>8.2f} bar\nNET WORK:      {w_net:>8.2f} kJ/kg\nEFFICIENCY:    {eta_cycle:>8.2f} %"
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Otto", rep, pd.DataFrame(pts), "pdf_o")


elif "Diesel" in ciclo:
    st.header("🛢️ Diesel Cycle Engine CAD")
    col_in, col_main = st.columns([1, 2.5], gap="large")
    with col_in:
        p1 = st.number_input("P1 Intake (bar)", value=1.0)
        t1 = st.number_input("T1 Intake (°C)", value=25.0)
        r = st.number_input("Compression Ratio r", value=18.0)
        rc = st.number_input("Cut-off Ratio rc", value=2.0)
        k = st.number_input("k (exp.)", value=1.4)
        cv = st.number_input("cv (kJ/kgK)", value=0.718)
        eta = st.number_input("η isentropic", value=0.85)

    rg = cv * (k - 1)
    cp = cv * k
    t1k = t1 + 273.15
    v1 = rg * t1k / (p1 * 100)
    v2 = v1 / r
    t2sk = t1k * (r ** (k - 1))
    t2k = t1k + (t2sk - t1k) / eta
    p2 = p1 * (t2k / t1k) * (v1 / v2)
    p3 = p2
    v3 = v2 * rc
    t3k = t2k * rc
    t4sk = t3k * ((v3 / v1) ** (k - 1))
    t4k = t3k - eta * (t3k - t4sk)
    p4 = p3 * (t4k / t3k) * (v3 / v1)

    pts = [
        {"name": "1", "P": p1, "T": t1, "h": cp*t1k, "s": cv*np.log(t1k/273.15), "v": v1},
        {"name": "2", "P": p2, "T": t2k-273.15, "h": cp*t2k, "s": cv*np.log(t2k/273.15)+rg*np.log(v2/v1), "v": v2},
        {"name": "3", "P": p3, "T": t3k-273.15, "h": cp*t3k, "s": cv*np.log(t3k/273.15)+rg*np.log(v3/v1), "v": v3},
        {"name": "4", "P": p4, "T": t4k-273.15, "h": cp*t4k, "s": cv*np.log(t4k/273.15), "v": v1},
        {"name": "1", "P": p1, "T": t1, "h": cp*t1k, "s": cv*np.log(t1k/273.15), "v": v1},
    ]
    q_in = cp * (t3k - t2k)
    q_out = cv * (t4k - t1k)
    w_net = q_in - q_out
    eta_cycle = 100.0 * w_net / q_in if q_in > 0 else 0

    with col_main:
        m1, m2, m3 = st.columns(3)
        m1.metric("Lavoro Netto", f"{w_net:.1f} kJ/kg")
        m2.metric("Rendimento", f"{eta_cycle:.2f} %")
        m3.metric("Pressione Max", f"{p3:.2f} bar")
        tab_flow, tab_pv, tab_ts, tab_rep = st.tabs(["Schema Motore", "P-v Diagram", "T-s Diagram", "Analysis Report"])
        with tab_flow: st.pyplot(draw_otto_diesel_schema(True))
        with tab_pv:
            fig = plotly_base("Diagramma P-v", "v (m³/kg)", "P (bar)")
            add_generic_points(fig, pts, "v", "P", "Ciclo Diesel", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)
        with tab_rep:
            rep = f"PEAK PRESSURE: {p3:>8.2f} bar\nNET WORK:      {w_net:>8.2f} kJ/kg\nEFFICIENCY:    {eta_cycle:>8.2f} %"
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Diesel", rep, pd.DataFrame(pts), "pdf_d")


elif "Frigorifero" in ciclo:
    st.header("❄️ Refrigeration Cycle CAD")
    col_in, col_main = st.columns([1, 2.5], gap="large")
    with col_in:
        te = st.number_input("T Evaporation (°C)", value=-15.0)
        tc = st.number_input("T Condensation (°C)", value=40.0)
        eta_c = st.number_input("η compressor", value=0.82)
        m_dot = st.number_input("Mass flow (kg/s)", value=0.5)

    pe, pc = 10**((te+100)/70), 10**((tc+100)/70)
    h1 = 404 + te*0.5
    h2s = h1 + (h1-200)*0.5*(pc/pe-1)
    h2 = h1 + (h2s-h1)/eta_c
    h3 = 200 + tc*1.2
    h4 = h3
    qe, wc = h1-h4, h2-h1
    cop = qe/wc if wc>0 else 0
    pts = [
        {"name": "1", "P": pe, "T": te, "h": h1, "s": 1.7+te*0.005, "v": 0},
        {"name": "2", "P": pc, "T": tc+30, "h": h2, "s": 1.75+tc*0.005, "v": 0},
        {"name": "3", "P": pc, "T": tc, "h": h3, "s": 1.0+tc*0.004, "v": 0},
        {"name": "4", "P": pe, "T": te, "h": h4, "s": 1.05+te*0.004, "v": 0},
        {"name": "1", "P": pe, "T": te, "h": h1, "s": 1.7+te*0.005, "v": 0},
    ]

    with col_main:
        m1, m2, m3 = st.columns(3)
        m1.metric("COP Freddo", f"{cop:.2f}")
        m2.metric("Pot. Frigo", f"{qe*m_dot:.1f} kW")
        m3.metric("Pot. Compr.", f"{wc*m_dot:.1f} kW")
        tab_ph, tab_ts, tab_rep = st.tabs(["P-h Diagram", "T-s Diagram", "Analysis Report"])
        with tab_ph:
            fig = plotly_base("Diagramma P-h", "h (kJ/kg)", "P (bar)", ylog=True)
            add_generic_points(fig, pts, "h", "P", "Ciclo Frigo", THEME["cyan"])
            st.plotly_chart(fig, use_container_width=True)
        with tab_rep:
            rep = f"COP REFRIG:  {cop:>8.2f}\nQ_EVAP:       {qe*m_dot:>8.2f} kW\nW_COMP:       {wc*m_dot:>8.2f} kW"
            st.markdown(f'<pre class="cad-report">{rep}</pre>', unsafe_allow_html=True)
            download_report_btn("Ciclo_Frigorifero", rep, pd.DataFrame(pts), "pdf_f")



else:
    st.header("🛠️ ThermoCAD")
    st.info(t["build_info"])

    with st.sidebar:
        st.divider()
        st.subheader("1. Punto indipendente")
        point_mode = st.selectbox("Metodo", ["P-T", "P-x", "P-s", "P-h", "T-x", "T-s"])
        val1 = st.number_input("Valore 1", value=1.0, format="%.4f", key="cad_v1")
        val2 = st.number_input("Valore 2", value=20.0, format="%.4f", key="cad_v2")
        if st.button("Aggiungi punto", use_container_width=True):
            args = {}
            if point_mode == "P-T":
                args = {"P": val1 / 10.0, "T": val2 + 273.15}
            elif point_mode == "P-x":
                args = {"P": val1 / 10.0, "x": val2}
            elif point_mode == "P-s":
                args = {"P": val1 / 10.0, "s": val2}
            elif point_mode == "P-h":
                args = {"P": val1 / 10.0, "h": val2}
            elif point_mode == "T-x":
                args = {"T": val1 + 273.15, "x": val2}
            elif point_mode == "T-s":
                args = {"T": val1 + 273.15, "s": val2}
            state = get_iapws_robust(**args)
            if state:
                st.session_state["cad_points"].append(steam_point(f"P{len(st.session_state['cad_points']) + 1}", state))
                st.rerun()
            else:
                st.error("Stato non valido")

        st.subheader("2. Punto derivato")
        if st.session_state["cad_points"]:
            point_names = [p["name"] for p in st.session_state["cad_points"]]
            base_name = st.selectbox("Punto di partenza", point_names)
            iso_type = st.selectbox("Trasformazione iso", ["Isobara", "Isoterma", "Isentropica", "Isentalpica"])
            target_prop = st.selectbox("Proprietà target", ["Pressione (bar)", "Temperatura (°C)", "Entropia (kJ/kgK)", "Entalpia (kJ/kg)", "Titolo x"])
            target_val = st.number_input("Valore target", value=1.0, format="%.4f", key="cad_target")
            if st.button("Aggiungi punto derivato", use_container_width=True):
                base_point = next(p for p in st.session_state["cad_points"] if p["name"] == base_name)
                args = {}
                if iso_type == "Isobara":
                    args["P"] = base_point["P"] / 10.0
                elif iso_type == "Isoterma":
                    args["T"] = base_point["T"] + 273.15
                elif iso_type == "Isentropica":
                    args["s"] = base_point["s"]
                elif iso_type == "Isentalpica":
                    args["h"] = base_point["h"]

                if "Pressione" in target_prop:
                    args["P"] = target_val / 10.0
                elif "Temperatura" in target_prop:
                    args["T"] = target_val + 273.15
                elif "Entropia" in target_prop:
                    args["s"] = target_val
                elif "Entalpia" in target_prop:
                    args["h"] = target_val
                elif "Titolo" in target_prop:
                    args["x"] = target_val

                state = get_iapws_robust(**args)
                if state:
                    st.session_state["cad_points"].append(steam_point(f"P{len(st.session_state['cad_points']) + 1}", state))
                    st.rerun()
                else:
                    st.error("Trasformazione non valida")

        st.checkbox("Chiudi il ciclo nei diagrammi", key="cad_close_cycle")
        if st.button("Rimuovi ultimo punto", use_container_width=True):
            if st.session_state["cad_points"]:
                st.session_state["cad_points"].pop()
                st.rerun()
        if st.button("Azzera ciclo", type="primary", use_container_width=True):
            st.session_state["cad_points"] = []
            st.rerun()

    if st.session_state["cad_points"]:
        points = list(st.session_state["cad_points"])
        closed_points = points + [points[0]] if st.session_state["cad_close_cycle"] and len(points) > 2 else points

        col_list, col_plot = st.columns([1, 1.8])
        with col_list:
            st.subheader(t["points"])
            render_point_table(points)
            st.subheader(t["stats"])
            if len(closed_points) > 1:
                q_in = 0.0
                q_out = 0.0
                l_net = 0.0
                for p_a, p_b in zip(closed_points[:-1], closed_points[1:]):
                    dh = p_b["h"] - p_a["h"]
                    l_net -= dh
                    if dh >= 0:
                        q_in += dh
                    else:
                        q_out += abs(dh)
                eta_cycle = 100.0 * l_net / q_in if q_in > 0 else 0.0
                st.metric(t["heat_in"], f"{q_in:.1f} kJ/kg")
                st.metric(t["heat_out"], f"{q_out:.1f} kJ/kg")
                st.metric(t["net_work"], f"{l_net:.1f} kJ/kg")
                st.metric(t["efficiency"], f"{eta_cycle:.2f} %")

        with col_plot:
            st.subheader(t["plots"])
            tab_ts, tab_pv, tab_tv, tab_hs = st.tabs(["T-s", "P-v", "T-v", "h-s"])
            with tab_ts:
                fig = plotly_base("T-s Diagram", "s (kJ/kgK)", "T (°C)")
                add_steam_dome(fig, "s", "T")
                add_steam_points(fig, closed_points, "s", "T", "Cycle", THEME["gold"])
                st.plotly_chart(fig, use_container_width=True)
            with tab_pv:
                fig = plotly_base("P-v Diagram", "v (m³/kg)", "P (bar)", xlog=True, ylog=True)
                add_steam_dome(fig, "v", "P")
                add_steam_points(fig, closed_points, "v", "P", "Cycle", THEME["cyan"])
                st.plotly_chart(fig, use_container_width=True)
            with tab_tv:
                fig = plotly_base("T-v Diagram", "v (m³/kg)", "T (°C)", xlog=True)
                add_steam_dome(fig, "v", "T")
                add_steam_points(fig, closed_points, "v", "T", "Cycle", THEME["green"])
                st.plotly_chart(fig, use_container_width=True)
            with tab_hs:
                fig = plotly_base("h-s Diagram", "s (kJ/kgK)", "h (kJ/kg)")
                add_steam_dome(fig, "s", "h")
                add_steam_points(fig, closed_points, "s", "h", "Cycle", THEME["red"])
                st.plotly_chart(fig, use_container_width=True)
    else:
        st.write("Aggiungi punti dalla barra laterale per iniziare a costruire il ciclo.")
